language: android
jdk: oraclejdk8
android:
	components:
        - tools
        - platform-tools
        - tools

        #Prueba
		- build-tools-26.1.0
		- android-26
        - extra
        
        #Gradle
        - ./gradlew build connectedCheck
        - gradle build connectedCheck
        
        # Additional components
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
        - addon-google_apis-google-26

        script:
           - ./gradlew clean rake:test

